// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class AuthUser
    {
        public AuthUser()
        {
            CandidatesCandidates = new HashSet<CandidatesCandidate>();
            CompaniesCompanyUserConsultors = new HashSet<CompaniesCompany>();
            CompaniesCompanyUsers = new HashSet<CompaniesCompany>();
            ComprasPaquetes = new HashSet<ComprasPaquete>();
            LoginUsers = new HashSet<LoginUser>();
            OpeningsOpenings = new HashSet<OpeningsOpening>();
            UsuariosRoles = new HashSet<UsuariosRole>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? LastLogin { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool IsSuperuser { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool IsStaff { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool IsActive { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime DateJoined { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Username { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ReasonCancellation { get; set; }
        public bool? IsNotifications { get; set; }
        public string Avatar { get; set; }
        public int? CountryId { get; set; }
        public int? CityId { get; set; }
        public string Workstation { get; set; }
        public string Team { get; set; }

        public virtual CatalogsState City { get; set; }
        public virtual CatalogsCountry Country { get; set; }
        public virtual ICollection<CandidatesCandidate> CandidatesCandidates { get; set; }
        public virtual ICollection<CompaniesCompany> CompaniesCompanyUserConsultors { get; set; }
        public virtual ICollection<CompaniesCompany> CompaniesCompanyUsers { get; set; }
        public virtual ICollection<ComprasPaquete> ComprasPaquetes { get; set; }
        public virtual ICollection<LoginUser> LoginUsers { get; set; }
        public virtual ICollection<OpeningsOpening> OpeningsOpenings { get; set; }
        public virtual ICollection<UsuariosRole> UsuariosRoles { get; set; }
    }
}