// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class AuthUserUserPermission
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int PermissionId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial155 { get; set; }

        public virtual AuthPermission Permission { get; set; }
    }
}