// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class BackOfficeContactservice
    {
        public BackOfficeContactservice()
        {
            BackOfficeContactservicesServices = new HashSet<BackOfficeContactservicesService>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Comments { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ContactName { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CountryId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial120 { get; set; }

        public virtual ICollection<BackOfficeContactservicesService> BackOfficeContactservicesServices { get; set; }
    }
}