// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class BackOfficeContactservicesService
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int ContactservicesId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CompanyserviceId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial123 { get; set; }

        public virtual BackOfficeContactservice Contactservices { get; set; }
    }
}