// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CandidatesCandidate
    {
        public CandidatesCandidate()
        {
            CandidatesCandidateAnswer2s = new HashSet<CandidatesCandidateAnswer2>();
            CandidatesCandidateExpAreas = new HashSet<CandidatesCandidateExpArea>();
            CandidatesCandidateExpSectors = new HashSet<CandidatesCandidateExpSector>();
            CandidatesCandidateInterests = new HashSet<CandidatesCandidateInterest>();
            CandidatesCandidateProfessions = new HashSet<CandidatesCandidateProfession>();
            CandidatesEducations = new HashSet<CandidatesEducation>();
            CandidatesLanguages = new HashSet<CandidatesLanguage>();
            CandidatesVolunteerexps = new HashSet<CandidatesVolunteerexp>();
            CandidatesWorkandsocialexps = new HashSet<CandidatesWorkandsocialexp>();
            OpeningsOpeningcandidates = new HashSet<OpeningsOpeningcandidate>();
            VisitasVacantes = new HashSet<VisitasVacante>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ProfId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Birthday { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Genre { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CountryId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Abilities { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Avaliability { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Extras { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? SalaryMax { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? SalaryMin { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Avatar { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int HeightField { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int WidthField { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Hobbies { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string VistedCountries { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialFacebook { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialLinkedin { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialSnapchat { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialTwitter { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialYoutube { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialSnapchatAvatar { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Competence1 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Competence2 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Competence3 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Skill1 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Skill2 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Skill3 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Answer1 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Answer3 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool TermsPolitics { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailJobOffers { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailSiteImprovements { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailUpdatesNewsMatteria { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string CustomUrl { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? HowHearAboutUsId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool FromTcs { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool FromTcsMailSent { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string CellphoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        public int? CurrencyId { get; set; }
        public string Position { get; set; }
        public string Positivechange { get; set; }
        public bool? Enable { get; set; }

        public virtual CatalogsCountry Country { get; set; }
        public virtual CatalogsCurrency Currency { get; set; }
        public virtual AuthUser User { get; set; }
        public virtual ICollection<CandidatesCandidateAnswer2> CandidatesCandidateAnswer2s { get; set; }
        public virtual ICollection<CandidatesCandidateExpArea> CandidatesCandidateExpAreas { get; set; }
        public virtual ICollection<CandidatesCandidateExpSector> CandidatesCandidateExpSectors { get; set; }
        public virtual ICollection<CandidatesCandidateInterest> CandidatesCandidateInterests { get; set; }
        public virtual ICollection<CandidatesCandidateProfession> CandidatesCandidateProfessions { get; set; }
        public virtual ICollection<CandidatesEducation> CandidatesEducations { get; set; }
        public virtual ICollection<CandidatesLanguage> CandidatesLanguages { get; set; }
        public virtual ICollection<CandidatesVolunteerexp> CandidatesVolunteerexps { get; set; }
        public virtual ICollection<CandidatesWorkandsocialexp> CandidatesWorkandsocialexps { get; set; }
        public virtual ICollection<OpeningsOpeningcandidate> OpeningsOpeningcandidates { get; set; }
        public virtual ICollection<VisitasVacante> VisitasVacantes { get; set; }
    }
}