// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CandidatesVolunteerexp
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string VolunteerFunction { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? VolunteerFrom { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? VolunteerTo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool ActualVolunteer { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CauseId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CandidateId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string VolunteerFromMonth { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string VolunteerFromYear { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string VolunteerToMonth { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string VolunteerToYear { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial208 { get; set; }

        public virtual CandidatesCandidate Candidate { get; set; }
    }
}