// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CandidatesEducation
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Institution { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Grade { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? StudiedFrom { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? StudiedTo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool ActualStudent { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string GroupAndActivities { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Discipline { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CandidateId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string StudiedFromMonth { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string StudiedFromYear { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string StudiedToMonth { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string StudiedToYear { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial198 { get; set; }
        public int? ProfessionId { get; set; }
        public string City { get; set; }
        public int? CountryId { get; set; }
        public string NameProfession { get; set; }

        public virtual CandidatesCandidate Candidate { get; set; }
    }
}