// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CandidatesCandidateInterest
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CandidateId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int InterestId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial191 { get; set; }

        public virtual CandidatesCandidate Candidate { get; set; }
        public virtual CatalogsInterest Interest { get; set; }
    }
}