// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CatalogsMailcontent
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string TitleEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Subject { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SubjectEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ContentEn { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
    }
}