// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CatalogsCountry
    {
        public CatalogsCountry()
        {
            AuthUsers = new HashSet<AuthUser>();
            CandidatesCandidates = new HashSet<CandidatesCandidate>();
            CompaniesCompanies = new HashSet<CompaniesCompany>();
            MetodosPagosCountries = new HashSet<MetodosPagosCountry>();
            OpeningsOpenings = new HashSet<OpeningsOpening>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Abreviation { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
        public string Image { get; set; }
        public string CodeCountry { get; set; }
        public decimal? AmountMoney { get; set; }
        public int? CurrencyId { get; set; }

        public virtual CatalogsCurrency Currency { get; set; }
        public virtual ICollection<AuthUser> AuthUsers { get; set; }
        public virtual ICollection<CandidatesCandidate> CandidatesCandidates { get; set; }
        public virtual ICollection<CompaniesCompany> CompaniesCompanies { get; set; }
        public virtual ICollection<MetodosPagosCountry> MetodosPagosCountries { get; set; }
        public virtual ICollection<OpeningsOpening> OpeningsOpenings { get; set; }
    }
}