// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CatalogsCurrency
    {
        public CatalogsCurrency()
        {
            CandidatesCandidates = new HashSet<CandidatesCandidate>();
            CatalogsCountries = new HashSet<CatalogsCountry>();
            FrontContentVacantesPaquetes = new HashSet<FrontContentVacantesPaquete>();
            OpeningsOpeningcandidates = new HashSet<OpeningsOpeningcandidate>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Abreviation { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string NameEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        public string NamePt { get; set; }

        public virtual ICollection<CandidatesCandidate> CandidatesCandidates { get; set; }
        public virtual ICollection<CatalogsCountry> CatalogsCountries { get; set; }
        public virtual ICollection<FrontContentVacantesPaquete> FrontContentVacantesPaquetes { get; set; }
        public virtual ICollection<OpeningsOpeningcandidate> OpeningsOpeningcandidates { get; set; }
    }
}