// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class CatalogsStatus
    {
        public CatalogsStatus()
        {
            OpeningsOpeningcandidates = new HashSet<OpeningsOpeningcandidate>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<OpeningsOpeningcandidate> OpeningsOpeningcandidates { get; set; }
    }
}