// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CatalogsCompanytype
    {
        public CatalogsCompanytype()
        {
            CompaniesCompanies = new HashSet<CompaniesCompany>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string NameEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string NamePt { get; set; }

        public virtual ICollection<CompaniesCompany> CompaniesCompanies { get; set; }
    }
}