// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class CatalogsTypeContract
    {
        public CatalogsTypeContract()
        {
            OpeningsOpenings = new HashSet<OpeningsOpening>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
        public bool? Active { get; set; }
        public DateTime? RegistrationDate { get; set; }

        public virtual ICollection<OpeningsOpening> OpeningsOpenings { get; set; }
    }
}