// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CompaniesCompany
    {
        public CompaniesCompany()
        {
            Creditos = new HashSet<Credito>();
            OpeningsOpenings = new HashSet<OpeningsOpening>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ContactName { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ContactEmail { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ContactPhoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ContactCellphoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Other { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CompanyTypeId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Website { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialFacebook { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialTwitter { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialLinkedin { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Logo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? HeightField { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? WidthField { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string OurImpactinfo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string BillingNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string BillingAddress { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string BillingCity { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string BillingPhoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? BillingCountryId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CountryId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool? Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string StatusCompany { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ServicesRegisterId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool TermsPolitics { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string BillingName { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailNewCandidates { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailOpeningsEnding { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailSiteImprovements { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool MailUpdatesNewsMatteria { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string CustomUrl { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? HowHearAboutUsId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ConsultantId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string SocialInstagram { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool FromTcs { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool FromTcsMailSent { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        public string OurAdn { get; set; }
        public string HowDidYouFindOut { get; set; }
        public int? UserConsultorId { get; set; }
        public bool? Approve { get; set; }

        public virtual CatalogsCompanytype CompanyType { get; set; }
        public virtual ConsultantsConsultant Consultant { get; set; }
        public virtual CatalogsCountry Country { get; set; }
        public virtual AuthUser User { get; set; }
        public virtual AuthUser UserConsultor { get; set; }
        public virtual ICollection<Credito> Creditos { get; set; }
        public virtual ICollection<OpeningsOpening> OpeningsOpenings { get; set; }
    }
}