// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CompaniesCompanyService
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CompanyId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CompanyserviceId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial250 { get; set; }
    }
}