// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class CompaniesCompanyuser
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string CellphoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CompanyId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial250 { get; set; }
    }
}