// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ComprasPaquete
    {
        public ComprasPaquete()
        {
            Creditos = new HashSet<Credito>();
            PagosPayPals = new HashSet<PagosPayPal>();
            PagosPeyus = new HashSet<PagosPeyu>();
        }

        public int Id { get; set; }
        public int IdProducto { get; set; }
        public int IdStatus { get; set; }
        public DateTime CreationDate { get; set; }
        public int? MetodoPagoId { get; set; }
        public int? UserId { get; set; }

        public virtual FrontContentVacantesPaquete IdProductoNavigation { get; set; }
        public virtual EstatusGenerale IdStatusNavigation { get; set; }
        public virtual MetodosPago MetodoPago { get; set; }
        public virtual AuthUser User { get; set; }
        public virtual ICollection<Credito> Creditos { get; set; }
        public virtual ICollection<PagosPayPal> PagosPayPals { get; set; }
        public virtual ICollection<PagosPeyu> PagosPeyus { get; set; }
    }
}