// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ConfiguracionCrearCuentaPostulante
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string LblNombre { get; set; }
        public string LblNombreEn { get; set; }
        public string LblNombrePt { get; set; }
        public string NombreHolder { get; set; }
        public string NombreHolderEn { get; set; }
        public string NombreHolderPt { get; set; }
        public string LblApellido { get; set; }
        public string LblApellidoEn { get; set; }
        public string LblApellidoPt { get; set; }
        public string ApellidoHolder { get; set; }
        public string ApellidoHolderEn { get; set; }
        public string ApellidoHolderPt { get; set; }
        public string LblGenero { get; set; }
        public string LblGeneroEn { get; set; }
        public string LblGeneroPt { get; set; }
        public string LblFechaNacimiento { get; set; }
        public string LblFechaNacimientoEn { get; set; }
        public string LblFechaNacimientoPt { get; set; }
        public string LblEmail { get; set; }
        public string LblEmailEn { get; set; }
        public string LblEmailPt { get; set; }
        public string LblContrasena { get; set; }
        public string LblContrasenaEn { get; set; }
        public string LblContrasenaPt { get; set; }
        public string LblRcontrasena { get; set; }
        public string LblRcontrasenaEn { get; set; }
        public string LblRcontrasenaPt { get; set; }
        public string LblTerminos { get; set; }
        public string LblTerminosEn { get; set; }
        public string LblTerminosPt { get; set; }
        public string BtnCuenta { get; set; }
        public string BtnCuentaEn { get; set; }
        public string BtnCuentaPt { get; set; }
        public string LblRequerido { get; set; }
        public string LblRequeridoEn { get; set; }
        public string LblRequeridoPt { get; set; }
        public string EmailNoValido { get; set; }
        public string EmailNovalidoEn { get; set; }
        public string EmailNovalidoPt { get; set; }
        public string RequiereTerminos { get; set; }
        public string RequiereTerminosEn { get; set; }
        public string RequiereTerminosPt { get; set; }
        public string PasswordValid { get; set; }
        public string PasswordValidEn { get; set; }
        public string PasswordValidPt { get; set; }
        public string LbListo { get; set; }
        public string LbListoEn { get; set; }
        public string LbListoPt { get; set; }
        public string LbMail { get; set; }
        public string LbMailEn { get; set; }
        public string LbMailPt { get; set; }
        public string LbCuenta { get; set; }
        public string LbCuentaEn { get; set; }
        public string LbCuentaPt { get; set; }
        public string BtnResend { get; set; }
        public string BtnResendEn { get; set; }
        public string BtnResendPt { get; set; }
        public string Btn { get; set; }
        public string BtnEn { get; set; }
        public string BtnPt { get; set; }
    }
}