// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ConfiguracionMisVacantesOrganizacion
    {
        public int Id { get; set; }
        public string LblMiPerfil { get; set; }
        public string LblMiPerfilEn { get; set; }
        public string LblMiPerfilPt { get; set; }
        public string UrlMiPerfil { get; set; }
        public string LblMisVacantes { get; set; }
        public string LblMisVacantesEn { get; set; }
        public string LblMisVacantesPt { get; set; }
        public string LblConfiguracion { get; set; }
        public string LblConfiguracionEn { get; set; }
        public string LblConfiguracionPt { get; set; }
        public string HolderBusqueda { get; set; }
        public string HolderBusquedaEn { get; set; }
        public string HolderBusquedaPt { get; set; }
        public string LblEditar { get; set; }
        public string LblEditarEn { get; set; }
        public string LblEditarPt { get; set; }
        public string LblTextCandidato { get; set; }
        public string LblTextCandidatoEn { get; set; }
        public string LblTextCandidatoPt { get; set; }
        public string LblPublicada { get; set; }
        public string LblPublicadaEn { get; set; }
        public string LblPublicadaPt { get; set; }
        public string LblStatus { get; set; }
        public string LblStatusEn { get; set; }
        public string LblStatusPt { get; set; }
        public string LblFechaPublica { get; set; }
        public string LblFechaPublicaEn { get; set; }
        public string LblFechaPublicaPt { get; set; }
        public string LblFechaCierre { get; set; }
        public string LblFechaCierreEn { get; set; }
        public string LblFechaCierrePt { get; set; }
        public string LblVisualiza { get; set; }
        public string LblVisualizaEn { get; set; }
        public string LblVisualizaPt { get; set; }
        public string LblPostulante { get; set; }
        public string LblPostulanteEn { get; set; }
        public string LblPostulantePt { get; set; }
        public string TitleVisualizacion { get; set; }
        public string TitleVisualizacionEn { get; set; }
        public string TitleVisualizacionPt { get; set; }
        public string LblSePostulo { get; set; }
        public string LblSePostuloEn { get; set; }
        public string LblSePostuloPt { get; set; }
        public string LblNombre { get; set; }
        public string LblNombreEn { get; set; }
        public string LblNombrePt { get; set; }
        public string LblPais { get; set; }
        public string LblPaisEn { get; set; }
        public string LblPaisPt { get; set; }
        public string LblCiudad { get; set; }
        public string LblCiudadEn { get; set; }
        public string LblCiudadPt { get; set; }
        public string LblIngresa { get; set; }
        public string LblIngresaEn { get; set; }
        public string LblIngresaPt { get; set; }
        public string LblTitlePostulacion { get; set; }
        public string LblTitlePostulacionEn { get; set; }
        public string LblTitlePostulacionPt { get; set; }
        public string LblModalNombre { get; set; }
        public string LblModalNombreEn { get; set; }
        public string LblModalNombrePt { get; set; }
        public string LblModalHomderNombre { get; set; }
        public string LblModalHomderNombreEn { get; set; }
        public string LblModalHomderNombrePt { get; set; }
        public string LblTodos { get; set; }
        public string LblTodosEn { get; set; }
        public string LblTodosPt { get; set; }
        public string LblRating { get; set; }
        public string LblRatingEn { get; set; }
        public string LblRatingPt { get; set; }
        public string LblModalPerfil { get; set; }
        public string LblModalPerfilEn { get; set; }
        public string LblModalPerfilPt { get; set; }
        public string LblSeleccionado { get; set; }
        public string LblSeleccionadoEn { get; set; }
        public string LblSeleccionadoPt { get; set; }
        public string LblPaisResidencia { get; set; }
        public string LblPaisResidenciaEn { get; set; }
        public string LblPaisResidenciaPt { get; set; }
        public string LblCiudadResidencia { get; set; }
        public string LblCiudadResidenciaEn { get; set; }
        public string LblCiudadResidenciaPt { get; set; }
        public string LblFechaNacimiento { get; set; }
        public string LblFechaNacimientoEn { get; set; }
        public string LblFechaNacimientoPt { get; set; }
        public string LblMomento { get; set; }
        public string LblMomentoEn { get; set; }
        public string LblMomentoPt { get; set; }
    }
}