// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ConfiguracionBusquedaVacantesPostulante
    {
        public int Id { get; set; }
        public string LblPostular { get; set; }
        public string LblPostularEn { get; set; }
        public string LblPostularPt { get; set; }
        public string LblDetallesVacante { get; set; }
        public string LblDetallesVacanteEn { get; set; }
        public string LblDetallesVacantePt { get; set; }
        public string LblSumarse { get; set; }
        public string LblSumarseEn { get; set; }
        public string LblSumarsePt { get; set; }
        public string LblOrganizacion { get; set; }
        public string LblOrganizacionEn { get; set; }
        public string LblOrganizacionPt { get; set; }
        public string LblResponsabilidad { get; set; }
        public string LblResponsabilidadEn { get; set; }
        public string LblResponsabilidadPt { get; set; }
        public string LblProposito { get; set; }
        public string LblPropositoEn { get; set; }
        public string LblPropositoPt { get; set; }
        public string LblDescripcionResponsabilidade { get; set; }
        public string LblDescripcionResponsabilidadeEn { get; set; }
        public string LblDescripcionResponsabilidadePt { get; set; }
        public string LblRequisito { get; set; }
        public string LblRequisitoEn { get; set; }
        public string LblRequisitoPt { get; set; }
        public string LblTipoContrato { get; set; }
        public string LblTipoContratoEn { get; set; }
        public string LblTipoContratoPt { get; set; }
        public string LblAreaTrabajo { get; set; }
        public string LblAreaTrabajoEn { get; set; }
        public string LblAreaTrabajoPt { get; set; }
        public string LblProfesiones { get; set; }
        public string LblProfesionesEn { get; set; }
        public string LblProfesionesPt { get; set; }
        public string LblNivelExperiencia { get; set; }
        public string LblNivelExperienciaEn { get; set; }
        public string LblNivelExperienciaPt { get; set; }
        public string LblCopiar { get; set; }
        public string LblCopiarEn { get; set; }
        public string LblCopiarPt { get; set; }
        public string LblLinkedin { get; set; }
        public string LblLinkedinEn { get; set; }
        public string LblLinkedinPt { get; set; }
        public string LblFacebook { get; set; }
        public string LblFacebookEn { get; set; }
        public string LblFacebookPt { get; set; }
        public string LblTwitter { get; set; }
        public string LblTwitterEn { get; set; }
        public string LblTwitterPt { get; set; }
        public string Toast { get; set; }
        public string ToastEn { get; set; }
        public string ToastPt { get; set; }
        public string ModalLbVolver { get; set; }
        public string ModalLbVolverEn { get; set; }
        public string ModalLbVolverPt { get; set; }
        public string ModalLbEnviar { get; set; }
        public string ModalLbEnviarEn { get; set; }
        public string ModalLbEnviarPt { get; set; }
        public string ModalSalarial { get; set; }
        public string ModalSalarialEn { get; set; }
        public string ModalSalarialPt { get; set; }
        public string ModalMoneda { get; set; }
        public string ModalMonedaEn { get; set; }
        public string ModalMonedaPt { get; set; }
        public string ModalDesde { get; set; }
        public string ModalDesdeEn { get; set; }
        public string ModalDesdePt { get; set; }
        public string ModalHasta { get; set; }
        public string ModalHastaEn { get; set; }
        public string ModalHastaPt { get; set; }
        public string SmallRequired { get; set; }
        public string SmallRequiredEn { get; set; }
        public string SmallRequiredPt { get; set; }
        public string PostulacionExito { get; set; }
        public string PostulacionExitoEn { get; set; }
        public string PostulacionExitoPt { get; set; }
        public string PostulacionDes { get; set; }
        public string PostulacionDesEn { get; set; }
        public string PostulacionDesPt { get; set; }
        public string PostulacionError { get; set; }
        public string PostulacionErrorEn { get; set; }
        public string PostulacionErrorPt { get; set; }
        public string PostulacionDesError { get; set; }
        public string PostulacionDesErrorEn { get; set; }
        public string PostulacionDesErrorPt { get; set; }
        public string MenuPerfil { get; set; }
        public string MenuPerfilEn { get; set; }
        public string MenuPerfilPt { get; set; }
        public string MenuMisPostulaciones { get; set; }
        public string MenuMisPostulacionesEn { get; set; }
        public string MenuMisPostulacionesPt { get; set; }
        public string MenuConfiguracion { get; set; }
        public string MenuConfiguracionEn { get; set; }
        public string MenuConfiguracionPt { get; set; }
        public string UrlMiPerfil { get; set; }
        public string UrlConfiguracion { get; set; }
        public string LblProceso { get; set; }
        public string LblProcesoEn { get; set; }
        public string LblProcesoPt { get; set; }
        public string LblFechaPostulado { get; set; }
        public string LblFechaPostuladoEn { get; set; }
        public string LblFechaPostuladoPt { get; set; }
    }
}