// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ConfiguracionPostulante
    {
        public int Id { get; set; }
        public string MenuMiPerfil { get; set; }
        public string MenuMiPerfilEn { get; set; }
        public string MenuMiPerfilPt { get; set; }
        public string MenuMisPostulaciones { get; set; }
        public string MenuMisPostulacionesEn { get; set; }
        public string MenuMisPostulacionesPt { get; set; }
        public string MenuConfiguracion { get; set; }
        public string MenuConfiguracionEn { get; set; }
        public string MenuConfiguracionPt { get; set; }
        public string SubtitleOne { get; set; }
        public string SubtitleOneEn { get; set; }
        public string SubtitleOnePt { get; set; }
        public string ActualPassword { get; set; }
        public string ActualPasswordEn { get; set; }
        public string ActualPasswordPt { get; set; }
        public string NewPassword { get; set; }
        public string NewPasswordEn { get; set; }
        public string NewPasswordPt { get; set; }
        public string ConfirmPassword { get; set; }
        public string ConfirmPasswordEn { get; set; }
        public string ConfirmPasswordPt { get; set; }
        public string PlaceHolders { get; set; }
        public string PlaceHoldersEn { get; set; }
        public string PlaceHoldersPt { get; set; }
        public string SmallsRequired { get; set; }
        public string SmallsRequiredEn { get; set; }
        public string SmallsRequiredPt { get; set; }
        public string SamllPassword { get; set; }
        public string SamllPasswordEn { get; set; }
        public string SamllPasswordPt { get; set; }
        public string BtnChangePassword { get; set; }
        public string BtnChangePasswordEn { get; set; }
        public string BtnChangePasswordPt { get; set; }
        public string SubtitleTwo { get; set; }
        public string SubtitleTwoEn { get; set; }
        public string SubtitleTwoPt { get; set; }
        public string SubTitleThree { get; set; }
        public string SubTitleThreeEn { get; set; }
        public string SubTitleThreePt { get; set; }
        public string Reasons { get; set; }
        public string ReasonsEn { get; set; }
        public string ReasonsPt { get; set; }
        public string BtnDelete { get; set; }
        public string BtnDeleteEn { get; set; }
        public string BtnDeletePt { get; set; }
        public string SubtitleFour { get; set; }
        public string SubtitleFourEn { get; set; }
        public string SubtitleFourPt { get; set; }
        public string NotificationBox { get; set; }
        public string NotificationBoxEn { get; set; }
        public string NotificationBoxPt { get; set; }
        public string ToastPasswordSuccess { get; set; }
        public string ToastPasswordSuccessEn { get; set; }
        public string ToastPasswordSuccessPt { get; set; }
        public string ToastPasswordError { get; set; }
        public string ToastPasswordErrorEn { get; set; }
        public string ToastPasswordErrorPt { get; set; }
        public string ToastNotificationActive { get; set; }
        public string ToastNotificationActiveEn { get; set; }
        public string ToastNotificationActivePt { get; set; }
        public string ToastNotificationInactive { get; set; }
        public string ToastNotificationInactiveEn { get; set; }
        public string ToastNotificationInactivePt { get; set; }
        public string UrlPerfil { get; set; }
        public string UrlMisPostulaciones { get; set; }
        public string UrlConfiguracion { get; set; }
    }
}