// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ConfiguracionPerfilOrganizacion
    {
        public int Id { get; set; }
        public string Pais { get; set; }
        public string PaisEn { get; set; }
        public string PaisPt { get; set; }
        public string Ciudad { get; set; }
        public string CiudadEn { get; set; }
        public string CiudadPt { get; set; }
        public string TipoOrganizacion { get; set; }
        public string TipoOrganizacionEn { get; set; }
        public string TipoOrganizacionPt { get; set; }
        public string FacebookHolder { get; set; }
        public string FacebookHolderEn { get; set; }
        public string FacebookHolderPt { get; set; }
        public string TwitterHolder { get; set; }
        public string TwitterHolderEn { get; set; }
        public string TwitterHolderPt { get; set; }
        public string InstagramHolder { get; set; }
        public string InstagramHolderEn { get; set; }
        public string InstagramHolderPt { get; set; }
        public string LinkedinHolder { get; set; }
        public string LinkedinHolderEn { get; set; }
        public string LinkedinHolderPt { get; set; }
        public string DatosContacto { get; set; }
        public string DatosContactoEn { get; set; }
        public string DatosContactoPt { get; set; }
        public string LblnombrePersona { get; set; }
        public string LblnombrePersonaEn { get; set; }
        public string LblnombrePersonaPt { get; set; }
        public string LblEmail { get; set; }
        public string LblEmailEn { get; set; }
        public string LblEmailPt { get; set; }
        public string LblTelFijo { get; set; }
        public string LblTelFijoEn { get; set; }
        public string LblTelFijoPt { get; set; }
        public string LblTelCel { get; set; }
        public string LblTelCelEn { get; set; }
        public string LblTelCelPt { get; set; }
        public string QuienesSomos { get; set; }
        public string QuienesSomosEn { get; set; }
        public string QuienesSomosPt { get; set; }
        public string ImpactoGenerado { get; set; }
        public string ImpactoGeneradoEn { get; set; }
        public string ImpactoGeneradoPt { get; set; }
        public string NuestroAdn { get; set; }
        public string NuestroAdnEn { get; set; }
        public string NuestroAdnPt { get; set; }
        public string MiPerfil { get; set; }
        public string MiPerfilEn { get; set; }
        public string MiPerfilPt { get; set; }
        public string LbldatosOrg { get; set; }
        public string LbldatosOrgEn { get; set; }
        public string LbldatosOrgPt { get; set; }
        public string LblDatosContacto { get; set; }
        public string LblDatosContactoEn { get; set; }
        public string LblDatosContactoPt { get; set; }
        public string LblQuienesSomos { get; set; }
        public string LblQuienesSomosEn { get; set; }
        public string LblQuienesSomosPt { get; set; }
        public string LblImpacto { get; set; }
        public string LblImpactoEn { get; set; }
        public string LblImpactoPt { get; set; }
        public string LblAdn { get; set; }
        public string LblAdnEn { get; set; }
        public string LblAdnPt { get; set; }
        public string LblEdit { get; set; }
        public string LblEditEn { get; set; }
        public string LblEditPt { get; set; }
        public string LblCancel { get; set; }
        public string LblCancelEn { get; set; }
        public string LblCancelPt { get; set; }
        public string LblSave { get; set; }
        public string LblSaveEn { get; set; }
        public string LblSavePt { get; set; }
    }
}