// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class ConsultantsConsultant
    {
        public ConsultantsConsultant()
        {
            CompaniesCompanies = new HashSet<CompaniesCompany>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Candidates { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Companies { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Consultants { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Openings { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Avatar { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? HeightField { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string IdNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime? Birthday { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string CellphoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Languages { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Linkedin { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PositionTeam { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Twitter { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? WidthField { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial250 { get; set; }

        public virtual ICollection<CompaniesCompany> CompaniesCompanies { get; set; }
    }
}