// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ContactsGeneral
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string NameCompany { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Comments { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public string Respuesta { get; set; }
    }
}