// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ContactoGeneralConfiguracion
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
        public string NameHolder { get; set; }
        public string NameHolderEn { get; set; }
        public string NameHolderPt { get; set; }
        public string SoyOrganizacion { get; set; }
        public string SoyOrganizacionEn { get; set; }
        public string SoyOrganizacionPt { get; set; }
        public string SoyPostulante { get; set; }
        public string SoyPostulanteEn { get; set; }
        public string SoyPostulantePt { get; set; }
        public string OrganizacionPertenece { get; set; }
        public string OrganizacionPerteneceEn { get; set; }
        public string OrganizacionPertenecePt { get; set; }
        public string OrganizacionPerteneceHolder { get; set; }
        public string OrganizacionPerteneceHoderEn { get; set; }
        public string OrganizacionPerteneceHolderPt { get; set; }
        public string Email { get; set; }
        public string EmailEn { get; set; }
        public string EmailPt { get; set; }
        public string EmailHolder { get; set; }
        public string EmailHolderEn { get; set; }
        public string EmailHolderPt { get; set; }
        public string LabelTelefono { get; set; }
        public string LabelTelefonoEn { get; set; }
        public string LabelTelefonoPt { get; set; }
        public string Comentarios { get; set; }
        public string ComentariosEn { get; set; }
        public string ComentariosPt { get; set; }
        public string ComentariosHolder { get; set; }
        public string ComentariosHolderEn { get; set; }
        public string ComentariosHolderPt { get; set; }
        public string Mensaje { get; set; }
        public string MensajeEn { get; set; }
        public string MensajePt { get; set; }
        public string Boton { get; set; }
        public string BotonEn { get; set; }
        public string BotonPt { get; set; }
        public string BotonEnviar { get; set; }
        public string BotonEnviarEn { get; set; }
        public string BotonEnviarPt { get; set; }
        public string SmallRequired { get; set; }
        public string SmallRequiredEn { get; set; }
        public string SmallRequiredPt { get; set; }
    }
}