// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class CrearCuentaOrganizacionConfiguracion
    {
        public int Id { get; set; }
        public string Tittle { get; set; }
        public string TittleEn { get; set; }
        public string TittlePt { get; set; }
        public string SubTittle { get; set; }
        public string SubTittleEn { get; set; }
        public string SubTittlePt { get; set; }
        public string InputOrganizationName { get; set; }
        public string InputOrganizationNameEn { get; set; }
        public string InputOrganizationNamePt { get; set; }
        public string PlaceHolderOrganizationName { get; set; }
        public string PlaceHolderOrganizationNameEn { get; set; }
        public string PlaceHolderOrganizationNamePt { get; set; }
        public string SmalltOrganizationName { get; set; }
        public string SmalltOrganizationNameEn { get; set; }
        public string SmalltOrganizationNamePt { get; set; }
        public string InputResponsable { get; set; }
        public string InputResponsableEn { get; set; }
        public string InputResponsablePt { get; set; }
        public string PlaceHolderResponsable { get; set; }
        public string PlaceHolderResponsableEn { get; set; }
        public string PlaceHolderResponsablePt { get; set; }
        public string SmallResponsable { get; set; }
        public string SmallResponsableEn { get; set; }
        public string SmallResponsablePt { get; set; }
        public string InputEmail { get; set; }
        public string InputEmailEn { get; set; }
        public string InputEmailPt { get; set; }
        public string PlaceHolderEmail { get; set; }
        public string PlaceHolderEmailEn { get; set; }
        public string PlaceHolderEmailPt { get; set; }
        public string SmallOneEmail { get; set; }
        public string SmallOneEmailEn { get; set; }
        public string SmallOneEmailPt { get; set; }
        public string SmallTwoEmail { get; set; }
        public string SmallTwoEmailEn { get; set; }
        public string SmallTwoEmailPt { get; set; }
        public string InputPassword { get; set; }
        public string InputPasswordEn { get; set; }
        public string InputPasswordPt { get; set; }
        public string PlaceHolderPassword { get; set; }
        public string PlaceHolderPasswordEn { get; set; }
        public string PlaceHolderPasswordPt { get; set; }
        public string SmallPassword { get; set; }
        public string SmallPasswordEn { get; set; }
        public string SmallPasswordPt { get; set; }
        public string InputConfirmPassword { get; set; }
        public string InputConfirmPasswordEn { get; set; }
        public string InputConfirmPasswordPt { get; set; }
        public string PlaceHolderConfirmPassword { get; set; }
        public string PlaceHolderConfirmPasswordEn { get; set; }
        public string PlaceHolderConfirmPasswordPt { get; set; }
        public string SmallOneConfirmPassword { get; set; }
        public string SmallOneConfirmPasswordEn { get; set; }
        public string SmallOneConfirmPasswordPt { get; set; }
        public string SmallTwoConfirmPassword { get; set; }
        public string SmallTwoConfirmPasswordEn { get; set; }
        public string SmallTwoConfirmPasswordPt { get; set; }
        public string ToastEmail { get; set; }
        public string ToastEmailEn { get; set; }
        public string ToastEmailPt { get; set; }
        public string Terminos { get; set; }
        public string TerminosEn { get; set; }
        public string TerminosPt { get; set; }
        public string SmallTerminos { get; set; }
        public string SmallTerminosEn { get; set; }
        public string SmallTerminosPt { get; set; }
        public string Ready { get; set; }
        public string ReadyEn { get; set; }
        public string ReadyPt { get; set; }
        public string Mail { get; set; }
        public string MailEn { get; set; }
        public string MailPt { get; set; }
        public string Activate { get; set; }
        public string ActivateEn { get; set; }
        public string ActivatePt { get; set; }
        public string Resend { get; set; }
        public string ResendEn { get; set; }
        public string ResendPt { get; set; }
    }
}