// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class Credito
    {
        public int Id { get; set; }
        public int IdCompany { get; set; }
        public int? IdOpening { get; set; }
        public int? IdCompra { get; set; }
        public int IdEstatus { get; set; }
        public DateTime? DateHighOpening { get; set; }
        public DateTime CreationDate { get; set; }
        public int? IdProducto { get; set; }

        public virtual CompaniesCompany IdCompanyNavigation { get; set; }
        public virtual ComprasPaquete IdCompraNavigation { get; set; }
        public virtual EstatusGenerale IdEstatusNavigation { get; set; }
        public virtual OpeningsOpening IdOpeningNavigation { get; set; }
        public virtual FrontContentVacantesPaquete IdProductoNavigation { get; set; }
    }
}