// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class DjangoContentType
    {
        public DjangoContentType()
        {
            AuthPermissions = new HashSet<AuthPermission>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string AppLabel { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Model { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial260 { get; set; }

        public virtual ICollection<AuthPermission> AuthPermissions { get; set; }
    }
}