// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class EstatusGenerale
    {
        public EstatusGenerale()
        {
            ComprasPaquetes = new HashSet<ComprasPaquete>();
            Creditos = new HashSet<Credito>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public bool? Active { get; set; }
        public string Color { get; set; }

        public virtual ICollection<ComprasPaquete> ComprasPaquetes { get; set; }
        public virtual ICollection<Credito> Creditos { get; set; }
    }
}