// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FontContentContenidoRecursosBlog
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public bool? Active { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public string TitleBlog { get; set; }
        public string TitleBogEn { get; set; }
        public string TitleBlogPt { get; set; }
        public string TitleContenido { get; set; }
        public string TitleContenidoEn { get; set; }
        public string TitleContenidoPt { get; set; }
        public string TitleConsejosPostulante { get; set; }
        public string TitleConsejosPostulanteEn { get; set; }
        public string TitleConsejosPostulantePt { get; set; }
        public string TitleCosejosOrg { get; set; }
        public string TitleConsejosOrgEn { get; set; }
        public string TitleConsejosOrgPt { get; set; }
        public string LeerMas { get; set; }
        public string LeerMasEn { get; set; }
        public string LeerMasPt { get; set; }
        public string LblActualidad { get; set; }
        public string LblActualidadEn { get; set; }
        public string LblActualidadPt { get; set; }
        public string TextActualidad { get; set; }
        public string TextActualidadEn { get; set; }
        public string TextActualidadPt { get; set; }
    }
}