// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class Footer
    {
        public Footer()
        {
            FooterDetails = new HashSet<FooterDetail>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public DateTime? CreationDate { get; set; }
        public string Url { get; set; }

        public virtual ICollection<FooterDetail> FooterDetails { get; set; }
    }
}