// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentReruitingPorQueContratarno
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public bool? Active { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string LblPorque { get; set; }
        public string LblPorqueEn { get; set; }
        public string LblPorquePt { get; set; }
    }
}