// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentConsultoriaOrganizacionalDetalle
    {
        public int Id { get; set; }
        public int ConsultoriaOrganizacionalId { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string MoreInfo { get; set; }
        public string MoreInfoEn { get; set; }
        public string MoreInfoPt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string MoreInfoLink { get; set; }
        public DateTime? CreationDate { get; set; }
        public string Imagen { get; set; }

        public virtual FrontContentConsultoriaOrganizacional ConsultoriaOrganizacional { get; set; }
    }
}