// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentComofuncionaAssessment
    {
        public FrontContentComofuncionaAssessment()
        {
            FrontContentComofuncionaAssessmentDetails = new HashSet<FrontContentComofuncionaAssessmentDetail>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public bool? Active { get; set; }
        public DateTime RegisterDate { get; set; }

        public virtual ICollection<FrontContentComofuncionaAssessmentDetail> FrontContentComofuncionaAssessmentDetails { get; set; }
    }
}