// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentComofuncionaDetailOnboarding
    {
        public int Id { get; set; }
        public int HeaderonboardingId { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }

        public virtual FrontContentManagerComofuncionaHeaderOnboarding Headeronboarding { get; set; }
    }
}