// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerBlog
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Titulo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Imagen { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Descripcion { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ArticuloUrl { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime ModificationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ModifiedById { get; set; }
        public string TituloEn { get; set; }
        public string TituloPt { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public int? Type { get; set; }
        public string Blog { get; set; }
        public string BlogEn { get; set; }
        public string BlogPt { get; set; }
        public string LeerMas { get; set; }
        public string LeerMasEn { get; set; }
        public string LeerMasPt { get; set; }
        public string ContenidoRecurso { get; set; }
        public string ContenidoRecursoEn { get; set; }
        public string ContenidoRecursoPt { get; set; }
    }
}