// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerMatteriainfo
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PorqueMateria { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PorqueMateriaEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia1 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia1En { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime ModificationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ModifiedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia2 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia2En { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia3 { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia3En { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Manifiesto { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ManifiestoEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeBoton { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeBotonEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia1Pt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia2Pt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Infografia3Pt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ManifiestoPt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeBotonPt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PorqueMateriaPt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial126 { get; set; }
    }
}