// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentEstructuraSalarial
    {
        public FrontContentEstructuraSalarial()
        {
            FrontContentEstructuraSalarialDetalles = new HashSet<FrontContentEstructuraSalarialDetalle>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string Image { get; set; }
        public string LinkMaterial { get; set; }
        public string ImageObjetivos { get; set; }
        public string TitlePoliticas { get; set; }
        public string TitlePoliticasEn { get; set; }
        public string TitlePoliticasPt { get; set; }
        public string ImagePoliticas { get; set; }
        public string DescriptionPoliticasShort { get; set; }
        public string DescriptionPoliticasShortEn { get; set; }
        public string DescriptionPoliticasShortPt { get; set; }
        public string DescriptionPoliticas { get; set; }
        public string DescriptionPoliticasEn { get; set; }
        public string DescriptionPoliticasPt { get; set; }
        public string ImgImpacto { get; set; }
        public bool Active { get; set; }
        public DateTime? CreationDate { get; set; }
        public string TitleImpacto { get; set; }
        public string TitleImpactoEn { get; set; }
        public string TitleImpactoPt { get; set; }
        public string TitleObjetivos { get; set; }
        public string TitleObjetivosEn { get; set; }
        public string TitleObjetivosPt { get; set; }
        public string BtnDownload { get; set; }
        public string BtnDownloadEn { get; set; }
        public string BtnDownloadPt { get; set; }

        public virtual ICollection<FrontContentEstructuraSalarialDetalle> FrontContentEstructuraSalarialDetalles { get; set; }
    }
}