// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerOfertasdestacada
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Titulo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Empresa { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Descripcion { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Imagen { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime ModificationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ModifiedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string DescripcionEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string TituloEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string UrlOpening { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial129 { get; set; }
    }
}