// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentPorqueMatterium
    {
        public FrontContentPorqueMatterium()
        {
            FrontContentPorqueMatteriaDetalles = new HashSet<FrontContentPorqueMatteriaDetalle>();
        }

        public int Id { get; set; }
        public string Phrase { get; set; }
        public string PhraseEn { get; set; }
        public string PhrasePt { get; set; }
        public string TitlePhrase { get; set; }
        public string TitlePhraseEn { get; set; }
        public string TitlePhrasePt { get; set; }
        public string Image { get; set; }
        public string TitleProfesionales { get; set; }
        public string TitleProfesionalesEn { get; set; }
        public string TitleProfesionalesPt { get; set; }
        public string DescriptionProfesionales { get; set; }
        public string DescriptionProfesionalesEn { get; set; }
        public string DescriptionProfesionalesPt { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreationDate { get; set; }
        public string TitleSeccion { get; set; }
        public string TitleSeccionEn { get; set; }
        public string TitleSeccionPt { get; set; }
        public string ImageSeccion { get; set; }
        public string LblVacantes { get; set; }
        public string LblVacantesEn { get; set; }
        public string LblVacantesPt { get; set; }

        public virtual ICollection<FrontContentPorqueMatteriaDetalle> FrontContentPorqueMatteriaDetalles { get; set; }
    }
}