// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentObjetivosAdnHeader
    {
        public FrontContentObjetivosAdnHeader()
        {
            FrontContentObjetivosAdns = new HashSet<FrontContentObjetivosAdn>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public bool? Active { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public string LblTitle { get; set; }
        public string LblTitleEn { get; set; }
        public string LblTitlePt { get; set; }
        public string LblTitleBeneficios { get; set; }
        public string LblTitleBeneficiosEn { get; set; }
        public string LblTitleBeneficiosPt { get; set; }

        public virtual ICollection<FrontContentObjetivosAdn> FrontContentObjetivosAdns { get; set; }
    }
}