// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentHomeImpactoPostulante
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Mentoria { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public bool Active { get; set; }
        public DateTime CreationDate { get; set; }
        public string MentoriaEn { get; set; }
        public string MentoriaPt { get; set; }
        public string MoreInfo { get; set; }
        public string MoreInfoEn { get; set; }
        public string MoreInfoPt { get; set; }
    }
}