// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerNuestrosservicio
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Servicio { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string ServicioEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Imagen { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Descripcion { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string DescripcionEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime ModificationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ModifiedById { get; set; }
        public string ServicioPt { get; set; }
        public string DescriptionPt { get; set; }
        public string Labelourservices { get; set; }
        public string LabelourservicesEn { get; set; }
        public string LabelourservicesPt { get; set; }
        public string MoreInfo { get; set; }
        public string MoreInfoEn { get; set; }
        public string MoreInfoPt { get; set; }
        public string Url { get; set; }
    }
}