// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentManifiestoMatterium
    {
        public int Id { get; set; }
        public string TitleHeader { get; set; }
        public string TitleHeaderEn { get; set; }
        public string TitleHeaderPt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string Image { get; set; }
        public string ImageCeo { get; set; }
        public string Phrase { get; set; }
        public bool? Active { get; set; }
        public string Name { get; set; }
        public string MarketStall { get; set; }
        public string Linkedin { get; set; }
        public string RegistrationDate { get; set; }
        public string RazonSer { get; set; }
        public string RazonSerEn { get; set; }
        public string RazonSerPt { get; set; }
        public string PhraseEn { get; set; }
        public string PhrasePt { get; set; }
        public string MarketStallEn { get; set; }
        public string MarketStallPt { get; set; }
        public string BtnOurAdn { get; set; }
        public string BtnOurAdnEn { get; set; }
        public string BtnOurAdnPt { get; set; }
    }
}