// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentManagerAliadosHeader
    {
        public int Id { get; set; }
        public string Phrase { get; set; }
        public string PhraseEn { get; set; }
        public string PhrasePt { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreationDate { get; set; }
    }
}