// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentTalleresHeader
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public bool? Active { get; set; }
        public DateTime? RegisterDate { get; set; }
        public string BtnContactanos { get; set; }
        public string BtnContactanosEn { get; set; }
        public string BtnContactanosPt { get; set; }
    }
}