// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentRecruitingComoEsHeader
    {
        public FrontContentRecruitingComoEsHeader()
        {
            FrontContentRecruitingComos = new HashSet<FrontContentRecruitingComo>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public bool? Active { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string TitleComoes { get; set; }
        public string TitleComoesEn { get; set; }
        public string TitleComoesPt { get; set; }

        public virtual ICollection<FrontContentRecruitingComo> FrontContentRecruitingComos { get; set; }
    }
}