// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentAnswer
    {
        public int Id { get; set; }
        public int PreguntaId { get; set; }
        public string Respuesta { get; set; }
        public string RespuestaEn { get; set; }
        public string RespuestaPt { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual FrontContentManagerFaq Pregunta { get; set; }
    }
}