// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentEnqueconsisteAdnHeader
    {
        public FrontContentEnqueconsisteAdnHeader()
        {
            FrontContentEnqueconsisteAdns = new HashSet<FrontContentEnqueconsisteAdn>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public bool? Active { get; set; }
        public DateTime? RegistrationDate { get; set; }
        public string LblEnqueConsiste { get; set; }
        public string LblEnqueConsisteEn { get; set; }
        public string LblEnqueConsistePt { get; set; }

        public virtual ICollection<FrontContentEnqueconsisteAdn> FrontContentEnqueconsisteAdns { get; set; }
    }
}