// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentPoliticasPrivacidad
    {
        public int Id { get; set; }
        public string Contenido { get; set; }
        public string ContenidoEn { get; set; }
        public string ContenidoPt { get; set; }
        public DateTime? CreationDate { get; set; }
    }
}