// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentVacantesComoFuncionaHeader
    {
        public FrontContentVacantesComoFuncionaHeader()
        {
            FrontContentVacantesComoFuncionas = new HashSet<FrontContentVacantesComoFunciona>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public bool? Active { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string BtnPublicar { get; set; }
        public string BtnPublicarEn { get; set; }
        public string BtnPublicarPt { get; set; }
        public string LblComoPublicar { get; set; }
        public string LblComoPublicarEn { get; set; }
        public string LblComoPublicarPt { get; set; }

        public virtual ICollection<FrontContentVacantesComoFunciona> FrontContentVacantesComoFuncionas { get; set; }
    }
}