// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerLogo
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Logo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string LogoEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string LogoFooter { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string LogoFooterEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime ModificationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ModifiedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string LogoFooterPt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string LogoPt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Trial126 { get; set; }
    }
}