// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentHomeHeaderPostulante
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string Image { get; set; }
        public string LinkVacantes { get; set; }
        public bool Active { get; set; }
        public DateTime CreationDate { get; set; }
        public string VerVacantes { get; set; }
        public string VerVacantesEn { get; set; }
        public string VerVacantesPt { get; set; }
        public string Destacada { get; set; }
        public string DestacadaEn { get; set; }
        public string DestacadaPt { get; set; }
    }
}