// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerNuestrosclientesinfo
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeImagen { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeImagenEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Imagen { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeBoton { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeBotonEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string TextoParrafo { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string TextoParrafoEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime ModificationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ModifiedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeBotonPt { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string MensajeImagenPt { get; set; }
        public string SectorPrivado { get; set; }
        public string SectorPrivadoEn { get; set; }
        public string SectorPrivadoPt { get; set; }
        public string SectorCivil { get; set; }
        public string SectorCivilEn { get; set; }
        public string SectorCivilPt { get; set; }
    }
}