// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class FrontContentManagerFaq
    {
        public FrontContentManagerFaq()
        {
            FrontContentAnswers = new HashSet<FrontContentAnswer>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Pregunta { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PreguntaEn { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CreationDate { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string PreguntaPt { get; set; }
        public byte? Type { get; set; }
        public bool? Active { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }

        public virtual ICollection<FrontContentAnswer> FrontContentAnswers { get; set; }
    }
}