// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentHomeOrgContenidoRecurso
    {
        public int Id { get; set; }
        public DateTime DateContent { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string LinkReadMore { get; set; }
        public string Share { get; set; }
        public bool Active { get; set; }
        public DateTime CreationDate { get; set; }
        public string Blog { get; set; }
        public string BlogEn { get; set; }
        public string BlogPt { get; set; }
        public string ContenidoRecurso { get; set; }
        public string ContenidoRecursoEn { get; set; }
        public string ContenidoRecursoPt { get; set; }
        public string LeerMas { get; set; }
        public string LeerMasEn { get; set; }
        public string LeerMasPt { get; set; }
    }
}