// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentRecruitingComo
    {
        public int Id { get; set; }
        public int? ComoesHeaderId { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public bool? Active { get; set; }

        public virtual FrontContentRecruitingComoEsHeader ComoesHeader { get; set; }
    }
}