// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentVacantesPaquete
    {
        public FrontContentVacantesPaquete()
        {
            ComprasPaquetes = new HashSet<ComprasPaquete>();
            Creditos = new HashSet<Credito>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public decimal RealPrice { get; set; }
        public decimal PackagePrice { get; set; }
        public bool? AplicaIva { get; set; }
        public int? CurrencyId { get; set; }
        public bool? Active { get; set; }
        public DateTime RegistrationDate { get; set; }
        public int NumberCredits { get; set; }
        public decimal? Savemoney { get; set; }
        public string LblPrecio { get; set; }
        public string LblPrecioEn { get; set; }
        public string LblPrecioPt { get; set; }
        public string LblAhorra { get; set; }
        public string LblAhorraEn { get; set; }
        public string LblAhorraPt { get; set; }

        public virtual CatalogsCurrency Currency { get; set; }
        public virtual ICollection<ComprasPaquete> ComprasPaquetes { get; set; }
        public virtual ICollection<Credito> Creditos { get; set; }
    }
}