// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentHomeGeneral
    {
        public int Id { get; set; }
        public string Video { get; set; }
        public string ImagePostulante { get; set; }
        public string ImageOrganizacion { get; set; }
        public string LinkMorePostulante { get; set; }
        public string LinkMoreOrganizacion { get; set; }
        public string BtnOrganizacionText { get; set; }
        public string BtnOrganizacionTextEn { get; set; }
        public string BtnOrganizacionTextPt { get; set; }
        public string BtnPostulanteText { get; set; }
        public string BtnPostulanteTextEn { get; set; }
        public string BtnPostulanteTextPt { get; set; }
        public string Labelimageorganizacion { get; set; }
        public string LabelimageorganizacionEn { get; set; }
        public string LabelimageorganizacionPt { get; set; }
        public string LabelimagePostulante { get; set; }
        public string LabelimagePostulanteEn { get; set; }
        public string LabelimagePostulantePt { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreationDate { get; set; }
    }
}