// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentPorqueMatteriaDetalle
    {
        public int Id { get; set; }
        public int PorquematteriaId { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public DateTime? CreationDate { get; set; }
        public int Type { get; set; }

        public virtual FrontContentPorqueMatterium Porquematteria { get; set; }
    }
}