// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentHeaderOrganizacione
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionPt { get; set; }
        public string Image { get; set; }
        public string LinkSeeMore { get; set; }
        public string LinkMoreInfo { get; set; }
        public string LinkSeeMoreEn { get; set; }
        public string LinkSeeMorePt { get; set; }
    }
}