// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class FrontContentHomeOrganizacionPorQueMatterium
    {
        public int Id { get; set; }
        public string DescriptionLong { get; set; }
        public string DescriptionLongPt { get; set; }
        public string DescriptionLongEn { get; set; }
        public string Number { get; set; }
        public string DescriptionShort { get; set; }
        public string DescriptionShortPt { get; set; }
        public string DescriptionShortEn { get; set; }
        public bool Active { get; set; }
        public DateTime CreateDate { get; set; }
        public string LabelDistintos { get; set; }
        public string LabelPorque { get; set; }
        public string MoreInfo { get; set; }
        public string LabelDistintosEn { get; set; }
        public string LabelDistintosPt { get; set; }
        public string LabelPorqueEn { get; set; }
        public string LabelPorquePt { get; set; }
        public string MoreInfoEn { get; set; }
        public string MoreInfoPt { get; set; }
    }
}