// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class IngresoOrganizacionConfiguracion
    {
        public int Id { get; set; }
        public string PlaceHolderEmail { get; set; }
        public string PlaceHolderEmailEn { get; set; }
        public string PlaceHolderEmailPt { get; set; }
        public string BtnLogIng { get; set; }
        public string BtnLogIngEn { get; set; }
        public string BtnLogIngPt { get; set; }
        public string BtnCreater { get; set; }
        public string BtnCreaterEn { get; set; }
        public string BtnCreaterPt { get; set; }
        public string PlaceHolderPassword { get; set; }
        public string PlaceHolderPasswordEn { get; set; }
        public string PlaceHolderPasswordPt { get; set; }
        public string ForgotePassword { get; set; }
        public string ForgotePasswordEn { get; set; }
        public string ForgotePasswordPt { get; set; }
        public string NoEmail { get; set; }
        public string NoEmailEn { get; set; }
        public string NoEmailPt { get; set; }
        public string EmailInvalid { get; set; }
        public string EmailInvalidEn { get; set; }
        public string EmailInvalidPt { get; set; }
        public string WrhiteEmail { get; set; }
        public string WrhiteEmailEn { get; set; }
        public string WrhiteEmailPt { get; set; }
        public string WhritePassword { get; set; }
        public string WhritePasswordEn { get; set; }
        public string WhritePasswordPt { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
    }
}