// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class LoginUser
    {
        public int Id { get; set; }
        public int? UsuarioId { get; set; }
        public DateTime? LoginDate { get; set; }

        public virtual AuthUser Usuario { get; set; }
    }
}