// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class MenuPrincipal
    {
        public MenuPrincipal()
        {
            MenuPrincipalDetalles = new HashSet<MenuPrincipalDetalle>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitlePt { get; set; }
        public int Type { get; set; }
        public DateTime? CreationDate { get; set; }
        public string Url { get; set; }

        public virtual ICollection<MenuPrincipalDetalle> MenuPrincipalDetalles { get; set; }
    }
}