// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class MetodosPago
    {
        public MetodosPago()
        {
            ComprasPaquetes = new HashSet<ComprasPaquete>();
            MetodosPagosCountries = new HashSet<MetodosPagosCountry>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Prefix { get; set; }
        public bool? Active { get; set; }
        public DateTime RegistrationDate { get; set; }

        public virtual ICollection<ComprasPaquete> ComprasPaquetes { get; set; }
        public virtual ICollection<MetodosPagosCountry> MetodosPagosCountries { get; set; }
    }
}