// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class MetodosPagosCountry
    {
        public int Id { get; set; }
        public int MetodoPagoId { get; set; }
        public int CountryId { get; set; }
        public DateTime RegistrationDate { get; set; }

        public virtual CatalogsCountry Country { get; set; }
        public virtual MetodosPago MetodoPago { get; set; }
    }
}