// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class NewsletterOrganizationFrontConfiguration
    {
        public int Id { get; set; }
        public string Suscribete { get; set; }
        public string SuscribeteEn { get; set; }
        public string SuscribetePt { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionEn { get; set; }
        public string DescripcionPt { get; set; }
        public string Nombre { get; set; }
        public string NombreEn { get; set; }
        public string NombrePt { get; set; }
        public string Email { get; set; }
        public string EmailEn { get; set; }
        public string EmailPt { get; set; }
        public string Organizacion { get; set; }
        public string OrganizacionEn { get; set; }
        public string OrganizacionPt { get; set; }
        public string Enviar { get; set; }
        public string EnviarEn { get; set; }
        public string EnviarPt { get; set; }
        public string ValidaEmailFormato { get; set; }
        public string ValidaEmailFormatoEn { get; set; }
        public string ValidaEmailFormatoPt { get; set; }
        public string ValidaNombre { get; set; }
        public string ValidaNombreEn { get; set; }
        public string ValidaNombrePt { get; set; }
        public string ValidaEmail { get; set; }
        public string ValidaEmailEn { get; set; }
        public string ValidaEmailPt { get; set; }
        public string ValidaOrganizacion { get; set; }
        public string ValidaOrganizacionEn { get; set; }
        public string ValidaOrganizacionPt { get; set; }
        public string Exito { get; set; }
        public string ExitoEn { get; set; }
        public string ExitoPt { get; set; }
    }
}