// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class NewsletterPostulantFrontConfiguration
    {
        public int Id { get; set; }
        public string Suscribete { get; set; }
        public string SuscribeteEn { get; set; }
        public string SuscribetePt { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionEn { get; set; }
        public string DescripcionPt { get; set; }
        public string Nombre { get; set; }
        public string NombreEn { get; set; }
        public string NombrePt { get; set; }
        public string Email { get; set; }
        public string EmailEn { get; set; }
        public string EmailPt { get; set; }
        public string Enviar { get; set; }
        public string EnviarEn { get; set; }
        public string EnviarPt { get; set; }
        public string ValidaEmail { get; set; }
        public string ValidaEmailEn { get; set; }
        public string ValidaEmailPt { get; set; }
        public string ValidaNombre { get; set; }
        public string ValidaNombreEn { get; set; }
        public string ValidaNombrePt { get; set; }
        public string EmailValido { get; set; }
        public string EmailValidoEn { get; set; }
        public string EmailValidoPt { get; set; }
    }
}