// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class OpeningsOpening
    {
        public OpeningsOpening()
        {
            Creditos = new HashSet<Credito>();
            OpeningsOpeningInterests = new HashSet<OpeningsOpeningInterest>();
            OpeningsOpeningProfessions = new HashSet<OpeningsOpeningProfession>();
            OpeningsOpeningcandidates = new HashSet<OpeningsOpeningcandidate>();
            VisitasVacantes = new HashSet<VisitasVacante>();
        }

        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int YearsExperience { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Avaliability { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? Salary { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime CloseOpening { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Activities { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Responsabilities { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string KeySkills { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string TeamProfile { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string Perks { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string RelevantDetails { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CompanyId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CountryId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime OpenOpening { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? ConsultantId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string AlternateCompanyAlias { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public string AlternateCompanyDescription { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool KeepCompanyAlias { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int OpeningTypeId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int YearsExperienceOpening { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CurrencyId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool PrivateSalary { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? HireType { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? PhaseId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int StatusOpening { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? TopLevel { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        public string Whyjoin { get; set; }
        public bool? SalaryTodefine { get; set; }
        public string PurposeOpening { get; set; }
        public int? WorkAreaId { get; set; }
        public bool? Featured { get; set; }
        public int? StatusProcess { get; set; }
        public int? UserId { get; set; }

        public virtual CompaniesCompany Company { get; set; }
        public virtual CatalogsCountry Country { get; set; }
        public virtual CatalogsTypeContract HireTypeNavigation { get; set; }
        public virtual EstatusVacante StatusOpeningNavigation { get; set; }
        public virtual EstatusVacantesProceso StatusProcessNavigation { get; set; }
        public virtual AuthUser User { get; set; }
        public virtual ICollection<Credito> Creditos { get; set; }
        public virtual ICollection<OpeningsOpeningInterest> OpeningsOpeningInterests { get; set; }
        public virtual ICollection<OpeningsOpeningProfession> OpeningsOpeningProfessions { get; set; }
        public virtual ICollection<OpeningsOpeningcandidate> OpeningsOpeningcandidates { get; set; }
        public virtual ICollection<VisitasVacante> VisitasVacantes { get; set; }
    }
}