// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    /// <summary>
    /// TRIAL
    /// </summary>
    public partial class OpeningsOpeningcandidate
    {
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public bool Status { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Timestamp { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public DateTime Updated { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int CandidateId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? CreatedById { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int OpeningId { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int Ranking { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? SalaryMax { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? SalaryMin { get; set; }
        /// <summary>
        /// TRIAL
        /// </summary>
        public int? UpdatedById { get; set; }
        public int? StatusPostulation { get; set; }
        public bool? Selected { get; set; }
        public int? Score { get; set; }
        public int? CurrencyId { get; set; }

        public virtual CandidatesCandidate Candidate { get; set; }
        public virtual CatalogsCurrency Currency { get; set; }
        public virtual OpeningsOpening Opening { get; set; }
        public virtual CatalogsStatus StatusPostulationNavigation { get; set; }
    }
}