// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class PagosPayPal
    {
        public int Id { get; set; }
        public int CompraId { get; set; }
        public string PaypalId { get; set; }
        public DateTime? CreateTime { get; set; }
        public string Status { get; set; }
        public string EmailAddress { get; set; }
        public string CurrencyCode { get; set; }
        public string MerchantId { get; set; }
        public int? Quantity { get; set; }
        public decimal? Amount { get; set; }
        public DateTime? RegistrationDate { get; set; }

        public virtual ComprasPaquete Compra { get; set; }
    }
}