// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class Pago
    {
        public int Id { get; set; }
        public int CompraId { get; set; }
        public string ExternalReference { get; set; }
        public int? TransactionOrderId { get; set; }
        public string MerchantOrderId { get; set; }
        public string IdMercadoPago { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public DateTime? DateApproved { get; set; }
        public decimal? NetReceivedAmount { get; set; }
        public decimal? TotalPaidAmount { get; set; }
        public string CurrencyId { get; set; }
        public DateTime? RegistrationDate { get; set; }
    }
}