// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class PagosPeyu
    {
        public int Id { get; set; }
        public int? CompraId { get; set; }
        public string OrderId { get; set; }
        public string TransactionId { get; set; }
        public decimal? Amount { get; set; }
        public string AuthorizationCode { get; set; }
        public string PendingReason { get; set; }
        public string ResponseCode { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string State { get; set; }
        public DateTime? RegistrationDate { get; set; }

        public virtual ComprasPaquete Compra { get; set; }
    }
}