// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class ProgramaMai
    {
        public int Id { get; set; }
        public string Video { get; set; }
        public string TitleMai { get; set; }
        public string TitleMaiEn { get; set; }
        public string TitleMaiPt { get; set; }
        public string DescriptionMai { get; set; }
        public string DescriptionMaiEn { get; set; }
        public string DescriptionMaiPt { get; set; }
        public string LinkMaterial { get; set; }
        public string ImageObjectives { get; set; }
        public string ImageManaged { get; set; }
        public string TitleManaged { get; set; }
        public string TitleManagedEn { get; set; }
        public string TitleManagedPt { get; set; }
        public string DescriptionManaged { get; set; }
        public string DescriptionManagedEn { get; set; }
        public string DescriptionManagedPt { get; set; }
        public bool Active { get; set; }
        public DateTime RegisterDate { get; set; }
        public string BtnDownload { get; set; }
        public string BtnDownloadEn { get; set; }
        public string BtnDownloadPt { get; set; }
        public string LblTitleObjetivos { get; set; }
        public string LblTitleObjetivosEn { get; set; }
        public string LblTitleObjetivosPt { get; set; }
    }
}