// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class Role
    {
        public Role()
        {
            UsuariosRoles = new HashSet<UsuariosRole>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual ICollection<UsuariosRole> UsuariosRoles { get; set; }
    }
}