// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class StepByStepPostulant
    {
        public StepByStepPostulant()
        {
            StepByStepPostulantDetails = new HashSet<StepByStepPostulantDetail>();
        }

        public int Id { get; set; }
        public string Step { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
        public int? NumberOrder { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual ICollection<StepByStepPostulantDetail> StepByStepPostulantDetails { get; set; }
    }
}