// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class StepByStepPostulantDetail
    {
        public int Id { get; set; }
        public int StepId { get; set; }
        public string Component { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NamePt { get; set; }
        public string Url { get; set; }
        public string PlaceHolder { get; set; }
        public string PlaceHolderEn { get; set; }
        public string PlaceHolderPt { get; set; }

        public virtual StepByStepPostulant Step { get; set; }
    }
}