// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;



namespace biz.matteria.Entities
{
    public partial class VisitasVacante
    {
        public int Id { get; set; }
        public int PostulanteId { get; set; }
        public int VacanteId { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual CandidatesCandidate Postulante { get; set; }
        public virtual OpeningsOpening Vacante { get; set; }
    }
}